// Credential vault protected by TOTP (2FA). The values live in VSCode's native
// SecretStorage (the OS keychain/credential manager) — never in
// plain text, never logged. Every sensitive operation (add/use/remove) requires
// a valid TOTP code, generated by an authenticator (Google Authenticator/Authy)
// the user enrolls via QR. The enrollment stores only the vault's TOTP secret.
import * as vscode from 'vscode';
import * as crypto from 'crypto';
import * as QRCode from 'qrcode';

// Keys in SecretStorage. Everything here is encrypted by the OS.
const K_TOTP = 'cockpit.creds.totp'; // segredo TOTP do cofre (base32) — presença = enrolado
const K_INDEX = 'cockpit.creds.index'; // JSON com os metadados (sem valores)
const K_VALUE = (id: string) => `cockpit.creds.v.${id}`; // valor de cada credencial

/** Metadata of a credential (never includes the secret value). */
export interface CredentialMeta {
  id: string;
  name: string;
  username?: string;
  note?: string;
  createdAt: number;
}

// --- TOTP (RFC 6238) -------------------------------------------------------

const B32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

function base32Encode(buf: Buffer): string {
  let bits = 0;
  let value = 0;
  let out = '';
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += B32[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31];
  return out;
}

function base32Decode(s: string): Buffer {
  const clean = s.toUpperCase().replace(/=+$/g, '').replace(/\s+/g, '');
  let bits = 0;
  let value = 0;
  const out: number[] = [];
  for (const ch of clean) {
    const idx = B32.indexOf(ch);
    if (idx < 0) continue; // ignora caracteres inválidos (tolerante)
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return Buffer.from(out);
}

/** Generates a new TOTP secret (20 random bytes in base32). */
export function generateTotpSecret(): string {
  return base32Encode(crypto.randomBytes(20));
}

/** Computes the 6-digit TOTP code for a counter (30s step). */
function hotp(secret: string, counter: number): string {
  const key = base32Decode(secret);
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64BE(BigInt(counter));
  const hmac = crypto.createHmac('sha1', key).update(buf).digest();
  const offset = hmac[hmac.length - 1] & 0x0f;
  const code =
    ((hmac[offset] & 0x7f) << 24) |
    ((hmac[offset + 1] & 0xff) << 16) |
    ((hmac[offset + 2] & 0xff) << 8) |
    (hmac[offset + 3] & 0xff);
  return (code % 1_000_000).toString().padStart(6, '0');
}

/** Verifies a TOTP code, accepting ±1 step (tolerance for clock drift). */
export function verifyTotp(secret: string, code: string, atMs = Date.now()): boolean {
  const clean = (code || '').replace(/\s+/g, '');
  if (!/^\d{6}$/.test(clean)) return false;
  const step = Math.floor(atMs / 1000 / 30);
  for (let w = -1; w <= 1; w++) {
    const counter = step + w;
    if (counter < 0) continue; // passo negativo (relógio ~época) não existe
    // Constant-time comparison so nothing leaks via timing.
    const expected = hotp(secret, counter);
    if (crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(clean))) return true;
  }
  return false;
}

/** otpauth:// URI for the authenticator (vault label + issuer). */
function otpauthUri(secret: string): string {
  const label = encodeURIComponent('Tootega Cockpit:cofre');
  const issuer = encodeURIComponent('Tootega Cockpit');
  return `otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`;
}

// --- Vault -----------------------------------------------------------------

export class CredentialsStore {
  // TOTP secret generated but NOT confirmed yet (waiting for the first valid code).
  // It stays in memory only; it becomes an enrollment on confirmation.
  private pendingTotp?: string;

  constructor(private readonly secrets: vscode.SecretStorage) {}

  /** Is there already an authenticator enrolled in the vault? */
  async isEnrolled(): Promise<boolean> {
    return !!(await this.secrets.get(K_TOTP));
  }

  /** Metadata of every credential (without values). */
  async list(): Promise<CredentialMeta[]> {
    const raw = await this.secrets.get(K_INDEX);
    if (!raw) return [];
    try {
      const arr = JSON.parse(raw) as CredentialMeta[];
      return Array.isArray(arr) ? arr : [];
    } catch {
      return [];
    }
  }

  private async saveIndex(items: CredentialMeta[]): Promise<void> {
    await this.secrets.store(K_INDEX, JSON.stringify(items));
  }

  /** Starts the enrollment: generates a secret, returns QR (SVG) + secret + URI. */
  async beginEnroll(): Promise<{ qrSvg: string; secret: string; uri: string }> {
    const secret = generateTotpSecret();
    this.pendingTotp = secret;
    const uri = otpauthUri(secret);
    const qrSvg = await QRCode.toString(uri, { type: 'svg', margin: 1, width: 180 });
    return { qrSvg, secret, uri };
  }

  /** Confirms the enrollment with the authenticator's first code. */
  async confirmEnroll(code: string): Promise<boolean> {
    const secret = this.pendingTotp;
    if (!secret || !verifyTotp(secret, code)) return false;
    await this.secrets.store(K_TOTP, secret);
    this.pendingTotp = undefined;
    return true;
  }

  /** Verifies a code against the enrolled secret. */
  private async verify(code: string): Promise<boolean> {
    const secret = await this.secrets.get(K_TOTP);
    if (!secret) return false;
    return verifyTotp(secret, code);
  }

  /** Adds a credential (requires a valid TOTP code). */
  async add(
    code: string,
    data: { name: string; username?: string; value: string; note?: string },
  ): Promise<{ ok: boolean; reason?: 'totp' | 'input' }> {
    if (!(await this.verify(code))) return { ok: false, reason: 'totp' };
    const name = data.name?.trim();
    const value = data.value ?? '';
    if (!name || !value) return { ok: false, reason: 'input' };
    const id = crypto.randomBytes(8).toString('hex');
    const items = await this.list();
    items.push({
      id,
      name,
      username: data.username?.trim() || undefined,
      note: data.note?.trim() || undefined,
      createdAt: Date.now(),
    });
    await this.secrets.store(K_VALUE(id), value);
    await this.saveIndex(items);
    return { ok: true };
  }

  /** Edits a credential (requires a valid TOTP code). Absent value = keep. */
  async edit(
    code: string,
    id: string,
    data: { name: string; username?: string; value?: string; note?: string },
  ): Promise<{ ok: boolean; reason?: 'totp' | 'input' }> {
    if (!(await this.verify(code))) return { ok: false, reason: 'totp' };
    const name = data.name?.trim();
    if (!name) return { ok: false, reason: 'input' };
    const items = await this.list();
    const idx = items.findIndex((c) => c.id === id);
    if (idx < 0) return { ok: false, reason: 'input' };
    items[idx] = {
      ...items[idx],
      name,
      username: data.username?.trim() || undefined,
      note: data.note?.trim() || undefined,
    };
    // Only rewrites the value when a new one was provided (empty field = keep).
    if (typeof data.value === 'string' && data.value.length > 0) {
      await this.secrets.store(K_VALUE(id), data.value);
    }
    await this.saveIndex(items);
    return { ok: true };
  }

  /** Retrieves a credential's value (requires a valid TOTP code). */
  async use(code: string, id: string): Promise<{ ok: boolean; value?: string; reason?: 'totp' }> {
    if (!(await this.verify(code))) return { ok: false, reason: 'totp' };
    const value = await this.secrets.get(K_VALUE(id));
    return { ok: true, value: value ?? '' };
  }

  /** Removes a credential (requires a valid TOTP code). */
  async remove(code: string, id: string): Promise<{ ok: boolean; reason?: 'totp' }> {
    if (!(await this.verify(code))) return { ok: false, reason: 'totp' };
    await this.secrets.delete(K_VALUE(id));
    const items = (await this.list()).filter((c) => c.id !== id);
    await this.saveIndex(items);
    return { ok: true };
  }
}
